version: '3'

services: 

    mytask3:
        image: bandrivskyi/task3
        ports: 
            - ${PORT_APP}
        environment:
            DEVOPS: ${DO_NAME} 
        working_dir: ${APP_HOME_DIR}
        restart: always
        links: 
            - db

    javaapp:
        image: groovy
        container_name: groovy
        working_dir: ${APP_JAVA_HOME_DIR}
        restart: always
        links: 
            - db
            - mytask3
            

    db:
        build: ./db
        container_name: mariadb
        volumes: 
            - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DB_NAME}
        ports: 
            - ${PORT_DB}
        restart: always