version: '3'

services: 

    mytask3:
        image: bandrivskyi/task3
        ports: 
            - ${APP_PORT}
        environment:
            DEVOPS: ${DO_NAME} 
        working_dir: ${APP_HOME_DIR}
        restart: always
        depends_on:
            - db
        deploy:
            mode: replicated
            replicas: 5

    javaapp:
        image: jenkins/jenkins:lts-jdk11
        container_name: jenkins
        working_dir: ${JENKINS_HOME_DIR} 
        ports:
            - ${JENKINS_CONNECT_PORT}
            - ${JENKINS_PORT}
        volumes: 
            - ${JENKINS_PATH_HOST}:${JENKINS_HOME_DIR}
        restart: always
        depends_on: 
            - db
            

    db:
        build: ./db
        container_name: mariadb
        volumes: 
            - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DB_NAME}
        ports: 
            - ${DB_PORT}
        restart: always