---
apiVersion: v1
kind: Secret
metadata:
  name: task8-secret
type: Opaque
data:
  SQL_USER: $SECRET_USER
  SQL_PASSWORD: $SECRET_PASSWORD
  POSTGRES_USER: $SECRET_USER
  POSTGRES_PASSWORD: $SECRET_PASSWORD
  SECRET_KEY: $SECRET_KEY
